spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      routes:
        - id: dishes-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/dishes/**
        - id: orders-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/orders/**
        - id: specials-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/special-dishes/**
server:
  port: 8080
